dev-python/gstreamer-player: add missing pygobject dependency
On a fresh install, gstreamer-player fails to load stating:
```
  File "/usr/lib/python3.10/site-packages/gsp/__init__.py", line 11, in <module>
    import gi  # pylint: disable=import-error
ModuleNotFoundError: No module named 'gi'
```

This is caused by a missing dependency to pull in pygobject. Explicitly adding the dependency should solve the issue.